# Generated by Django 3.2.7 on 2021-11-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name': 'Habitacion', 'verbose_name_plural': 'Habitaciones'},
        ),
    ]
