# Generated by Django 3.2.7 on 2021-11-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agencia_de_viaje', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencia_de_viaje',
            options={'verbose_name': 'Agencia_de_viaje', 'verbose_name_plural': 'Agencia_de_viajes'},
        ),
    ]
