# Generated by Django 3.2.9 on 2021-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agencia_de_viaje', '0002_alter_agencia_de_viaje_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia_de_viaje',
            name='Ciudad',
            field=models.CharField(max_length=50),
        ),
    ]
