# Generated by Django 3.2.7 on 2021-09-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=45)),
                ('Año_contruccion', models.CharField(max_length=10)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categoria.categoria')),
            ],
        ),
    ]
