# Generated by Django 3.2.7 on 2021-09-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
        ('Hotel', '0001_initial'),
        ('Agencia_de_viaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_ingreso', models.DateField()),
                ('Fecha_salida', models.DateField()),
                ('Hora_ingreso', models.CharField(max_length=30)),
                ('Agencia_de_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencia_de_viaje.agencia_de_viaje')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel')),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.persona')),
            ],
        ),
    ]
