# Generated by Django 3.2.7 on 2021-11-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0003_auto_20211118_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_ingreso',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_salida',
            field=models.CharField(max_length=30),
        ),
    ]
