# Generated by Django 3.2.7 on 2021-11-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0004_auto_20211118_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_ingreso',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_salida',
            field=models.DateTimeField(),
        ),
    ]
